name: equia
description: Equia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ###########################
  # MODULES

  domain:
    path: domain

  data:
    path: data

  ###########################
  # PLUGINS AND PACKAGES

  intl: any
  cupertino_icons: any
  flutter_bloc: any
  auto_route: any
  equatable: any
  flutter_launcher_icons: any
  cached_network_image: any
  font_awesome_flutter: any
  auto_size_text: any
  url_launcher: any
  package_info_plus: any
  formz: 0.4.1
  tutorial_coach_mark: ^1.2.4
  awesome_notifications: any
  amplitude_flutter: any
  firebase_core: ^2.21.0
  firebase_crashlytics: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  injectable_generator: any
  flutter_lints: any

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    - assets/

  #flutter_icons:
  #  android: true
  #  ios: true
  #  image_path: "assets/app_icon.jpeg"
